import pyautogui as pg
import time

# Step 1: Introduction
print("This program will send automated messages on WhatsApp Web.")
print("You have 10 seconds to open the chat where you want to send messages.")
time.sleep(10)

# Step 2: Set your message and number of repetitions
message = "Hello Guys! This is an auto message. Generated by Python."
repeat = 20  # You can change this to any number

# Step 3: Loop to send the message
for i in range(repeat):
    pg.write(message)     # types the message
    pg.press("enter")     # presses Enter to send
    time.sleep(0.5)       # small delay between messages
